import './globals.css';
import type { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import { Footer, Navbar } from '@/components';

const fira = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: { locale: 'en' | 'ro' };
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={`${fira.className} bg-primary-light`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
