import './globals.css';
import type { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import { Footer, Navbar } from '@/components';

const fira = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Navbar />
      <body className={`${fira.className} bg-primary-light`}>{children}</body>
      <Footer />
    </section>
  );
}
